### PR TITLE
Add Dapptools Tutorial

### LINKED ISSUE #77: Add dapptools tutorial
Inspired by the hardhat and truffle tutorials, I believe that there should be a basic tutorial on how to get started with Dapptools for Optimism.

### PR DESCRIPTION
**Pull request by tonykogias**
Created a basic tutorial with Dapptools on how to get started testing and deploying smart contracts on the Optimistic network. Inspired by the hardhat and truffle tutorials.

- Fixes #77

### CODE REVIEW

**Comment by qbzzt** [comment]
I ran exactly according to the directions and got this error:

```
ori@dapp-tools-tut:~/dapp/dapp$ dapp test --rpc
dapp-test: rpc block: latest
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
hevm: HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 8545
  secure               = True
  requestHeaders       = [("Content-Type","application/json"),("User-Agent","haskell wreq-0.5.3.3")]
  path                 = "/"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed (Error_Packet_Parsing "Failed reading: invalid header type: 72\nFrom:\theader\n\n")))
ori@dapp-tools-tut:~/dapp/dapp$
```

I think this is something in the SSL settings, but I don't know NIX well enough to solve it.

**Comment by tonykogias** [comment]
Thanks for catching that! I changed the rpc url from https to http, it should work now.

**Comment by qbzzt** [comment]
> Thanks for catching that! I changed the rpc url from https to http, it should work now.

It does work. I should have realized that was the problem, but when I pretend to be a clueless user I sometimes go too far ;-)

Speaking of clueless users, I think it would be better if the README.md had step by step directions for how to create a key file and import your private key. Some readers are noobs. Do you want to write it, or would you rather I did?

**Comment by qbzzt** [comment]
PS
--
Thank you! This really is a good tutorial. I'm just nitpicky and pedantic because I'm a technical writer and it comes with the territory.

**Comment by tonykogias** [comment]
> It does work. I should have realized that was the problem, but when I pretend to be a clueless user I sometimes go too far ;-)
> 
> Speaking of clueless users, I think it would be better if the README.md had step by step directions for how to create a key file and import your private key. Some readers are noobs. Do you want to write it, or would you rather I did?

I totally agree! I added a few more details, please let me know if that works for you.

**Comment by qbzzt** [comment]
Thank you. Another issue. I decided not to write anything but just use the source code in the repository. I got:

```
ori@dapp-tools-tut:~/optimism-tutorial/dapptools/dapp$ export ETH_RPC_URL=http://127.0.0.1:8545
ori@dapp-tools-tut:~/optimism-tutorial/dapptools/dapp$ dapp test --rpc
dapp-remappings: error: ./lib/ds-test is not a Git repository
dapp-remappings: error: try "dapp update" to initialize submodules
ParserError: Source "ds-test/test.sol" not found: File not found.
 --> src/Dapp.t.sol:4:1:
  |
4 | import "ds-test/test.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

```

It is created by `dapp init`, but only in an empty directory. When I try it in `dapptools/dapp` I get an empty `lib/ds-test`:

```
ori@dapp-tools-tut:~/optimism-tutorial/dapptools/dapp$ dapp init
dapp-remappings: error: ./lib/ds-test is not a Git repository
dapp-remappings: error: try "dapp update" to initialize submodules
+ git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint:   git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint:   git branch -m <name>
Initialized empty Git repository in /home/ori/optimism-tutorial/dapptools/dapp/.git/
+ mkdir -p lib src
+ git add .gitignore
+ git commit -m 'dapp init Dapp'
[master (root-commit) 6518427] dapp init Dapp
 6 files changed, 54 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 .gitignore
 create mode 100644 .gitmodules
 create mode 100644 Makefile
 create mode 100644 src/Dapp.sol
 create mode 100644 src/Dapp.t.sol
+ dapp install ds-test
+ git submodule add --force https://github.com/dapphub/ds-test lib/ds-test
'lib/ds-test' already exists and is not a valid git repo
ori@dapp-tools-tut:~/optimism-tutorial/dapptools/dapp$ 
```

If you remove the `lib/` directory it works.

I'll check the `ethsign` later today.

**Comment by tonykogias** [comment]
I pushed a fix, please let me know if it works now.

**Comment by qbzzt** [comment]
> `[Update README.md](/ethereum-optimism/optimism-tutorial/pull/78/commits/eb77408981fc1db6b9de4e8d1e2956ed32b45a81) `
> Verified
> ` [eb77408](/ethereum-optimism/optimism-tutorial/pull/78/commits/eb77408981fc1db6b9de4e8d1e2956ed32b45a81) `

It works. As far as I'm concerned, this is ready for merge.

**Review by qbzzt — APPROVED** [review]
Good job, thank you!

**Comment by smartcontracts** [comment]
@tonykogias if you send me your eth address I'll draw you a custom contributor NFT :-)

**Comment by tonykogias** [comment]
> @tonykogias if you send me your eth address I'll draw you a custom contributor NFT :-)

That's great! Thanks 0xd71500AD407dCcEe1C0d1a0Cd34E2707835Bea8D

**Pull request merged**
